# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('ra', models.AutoField(primary_key=True, serialize=False, verbose_name='ra')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('email', models.CharField(max_length=80, verbose_name='email')),
                ('celular', models.CharField(max_length=11, verbose_name='celular')),
                ('sigla_curso', models.CharField(max_length=5, verbose_name='sigla_curso')),
            ],
            options={
                'db_table': 'aluno',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('sigla', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='sigla')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='nome')),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('nome', models.CharField(max_length=240, primary_key=True, serialize=False, verbose_name='nome')),
                ('carga_horaria', models.IntegerField()),
                ('teoria', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pratica', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ementa', models.CharField(max_length=500, verbose_name='ementa')),
                ('competencias', models.CharField(max_length=500, verbose_name='competencias')),
                ('habilidades', models.CharField(max_length=500, verbose_name='habilidades')),
                ('conteudo', models.CharField(max_length=500, verbose_name='conteudo')),
                ('bibliografia_basica', models.CharField(max_length=500, verbose_name='bibliografia basica')),
                ('bibliografia_complementar', models.CharField(max_length=500, verbose_name='bibliografia complementar')),
            ],
            options={
                'db_table': 'disciplina',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('ra', models.AutoField(primary_key=True, serialize=False, verbose_name='ra')),
                ('apelido', models.CharField(max_length=30, unique=True, verbose_name='apelido')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('email', models.CharField(max_length=80, verbose_name='email')),
                ('celular', models.CharField(max_length=11, verbose_name='celular')),
            ],
            options={
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='Cursoturma',
            fields=[
                ('sigla_curso', models.OneToOneField(db_column='sigla_curso', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lms.Curso')),
            ],
            options={
                'db_table': 'cursoturma',
            },
        ),
        migrations.CreateModel(
            name='Disciplinaofertada',
            fields=[
                ('nome_disciplina', models.OneToOneField(db_column='nome_disciplina', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lms.Disciplina')),
                ('ano', models.SmallIntegerField()),
                ('semestre', models.CharField(max_length=1, verbose_name='semestre')),
            ],
            options={
                'db_table': 'disciplinaofertada',
            },
        ),
        migrations.CreateModel(
            name='Gradecurricular',
            fields=[
                ('sigla_curso', models.OneToOneField(db_column='sigla_curso', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lms.Curso')),
                ('ano', models.SmallIntegerField()),
                ('semestre', models.CharField(max_length=1, verbose_name='semestre')),
            ],
            options={
                'db_table': 'gradecurricular',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('ra_aluno', models.OneToOneField(db_column='ra_aluno', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lms.Aluno')),
            ],
            options={
                'db_table': 'matricula',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('sigla_curso', models.OneToOneField(db_column='sigla_curso', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lms.Gradecurricular')),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'periodo',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('nome_disciplina', models.OneToOneField(db_column='nome_disciplina', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lms.Disciplinaofertada')),
                ('id', models.CharField(max_length=1, verbose_name='id')),
                ('turno', models.CharField(max_length=15, verbose_name='turno')),
            ],
            options={
                'db_table': 'turma',
            },
        ),
        migrations.AlterUniqueTogether(
            name='gradecurricular',
            unique_together=set([('sigla_curso', 'ano', 'semestre')]),
        ),
        migrations.AlterUniqueTogether(
            name='disciplinaofertada',
            unique_together=set([('nome_disciplina', 'ano', 'semestre')]),
        ),
        migrations.CreateModel(
            name='Periododisciplina',
            fields=[
                ('sigla_curso', models.OneToOneField(db_column='sigla_curso', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lms.Periodo')),
            ],
            options={
                'db_table': 'periododisciplina',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('nome_disciplina', models.OneToOneField(db_column='nome_disciplina', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lms.Turma')),
                ('numero', models.IntegerField()),
                ('data_limite_entrega', models.DateField()),
                ('descricao', models.CharField(max_length=500, verbose_name='descricao')),
                ('dta', models.DateField()),
            ],
            options={
                'db_table': 'questao',
            },
        ),
        migrations.AddField(
            model_name='turma',
            name='ano_ofertado',
            field=models.ForeignKey(db_column='ano_ofertado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Turma.ano_ofertado+', to='lms.Disciplinaofertada'),
        ),
        migrations.AddField(
            model_name='turma',
            name='ra_professor',
            field=models.ForeignKey(db_column='ra_professor', on_delete=django.db.models.deletion.DO_NOTHING, to='lms.Professor'),
        ),
        migrations.AddField(
            model_name='turma',
            name='semestre_ofertado',
            field=models.ForeignKey(db_column='semestre_ofertado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Turma.semestre_ofertado+', to='lms.Disciplinaofertada'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='ano_grade',
            field=models.ForeignKey(db_column='ano_grade', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Periodo.ano_grade+', to='lms.Gradecurricular'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='semestre_grade',
            field=models.ForeignKey(db_column='semestre_grade', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Periodo.semestre_grade+', to='lms.Gradecurricular'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ano_ofertado',
            field=models.ForeignKey(db_column='ano_ofertado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Matricula.ano_ofertado+', to='lms.Turma'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='id_turma',
            field=models.ForeignKey(db_column='id_turma', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Matricula.id_turma+', to='lms.Turma'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='nome_disciplina',
            field=models.ForeignKey(db_column='nome_disciplina', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Matricula.nome_disciplina+', to='lms.Turma'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='semestre_ofertado',
            field=models.ForeignKey(db_column='semestre_ofertado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Matricula.semestre_ofertado+', to='lms.Turma'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='ano_ofertado',
            field=models.ForeignKey(db_column='ano_ofertado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Cursoturma.ano_ofertado+', to='lms.Turma'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='id_turma',
            field=models.ForeignKey(db_column='id_turma', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Cursoturma.id_turma+', to='lms.Turma'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='nome_disciplina',
            field=models.ForeignKey(db_column='nome_disciplina', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Cursoturma.nome_disciplina+', to='lms.Turma'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='semestre_ofertado',
            field=models.ForeignKey(db_column='semestre_ofertado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Cursoturma.semestre_ofertado+', to='lms.Turma'),
        ),
        migrations.CreateModel(
            name='Arquivoquestao',
            fields=[
                ('nome_disciplina', models.OneToOneField(db_column='nome_disciplina', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lms.Questao')),
                ('arquivo', models.CharField(max_length=500, verbose_name='arquivo')),
            ],
            options={
                'db_table': 'arquivoquestao',
            },
        ),
        migrations.CreateModel(
            name='Arquivoresposta',
            fields=[
                ('nome_disciplina', models.OneToOneField(db_column='nome_disciplina', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lms.Questao')),
                ('arquivo', models.CharField(max_length=500, verbose_name='arquivo')),
            ],
            options={
                'db_table': 'arquivoresposta',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('nome_disciplina', models.OneToOneField(db_column='nome_disciplina', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lms.Questao')),
                ('data_avaliacao', models.DateField()),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='nota')),
                ('avaliacao', models.CharField(max_length=500, verbose_name='avaliacao')),
                ('descricao', models.CharField(max_length=500, verbose_name='descricao')),
                ('data_de_envio', models.DateField()),
            ],
            options={
                'db_table': 'resposta',
            },
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together=set([('nome_disciplina', 'ano_ofertado', 'semestre_ofertado', 'id')]),
        ),
        migrations.AddField(
            model_name='questao',
            name='ano_ofertado',
            field=models.ForeignKey(db_column='ano_ofertado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Questao.ano_ofertado+', to='lms.Turma'),
        ),
        migrations.AddField(
            model_name='questao',
            name='id_turma',
            field=models.ForeignKey(db_column='id_turma', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Matricula.id_turma+', to='lms.Turma'),
        ),
        migrations.AddField(
            model_name='questao',
            name='semestre_ofertado',
            field=models.ForeignKey(db_column='semestre_ofertado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Questao.semestre_ofertado+', to='lms.Turma'),
        ),
        migrations.AddField(
            model_name='periododisciplina',
            name='ano_grade',
            field=models.ForeignKey(db_column='ano_grade', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Periododisciplina.ano_grade+', to='lms.Periodo'),
        ),
        migrations.AddField(
            model_name='periododisciplina',
            name='nome_disciplina',
            field=models.ForeignKey(db_column='nome_disciplina', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Periododisciplina.nome_disciplina+', to='lms.Disciplina'),
        ),
        migrations.AddField(
            model_name='periododisciplina',
            name='numero_periodo',
            field=models.ForeignKey(db_column='numero_periodo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Periododisciplina.numero_periodo+', to='lms.Periodo'),
        ),
        migrations.AddField(
            model_name='periododisciplina',
            name='semestre_grade',
            field=models.ForeignKey(db_column='semestre_grade', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Periododisciplina.semestre_grade+', to='lms.Periodo'),
        ),
        migrations.AlterUniqueTogether(
            name='periodo',
            unique_together=set([('sigla_curso', 'ano_grade', 'semestre_grade', 'numero')]),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together=set([('ra_aluno', 'nome_disciplina', 'ano_ofertado', 'id_turma')]),
        ),
        migrations.AlterUniqueTogether(
            name='cursoturma',
            unique_together=set([('sigla_curso', 'nome_disciplina', 'ano_ofertado', 'semestre_ofertado', 'id_turma')]),
        ),
        migrations.AddField(
            model_name='resposta',
            name='ano_ofertado',
            field=models.ForeignKey(db_column='ano_ofertado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Resposta.ano_ofertado+', to='lms.Questao'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='id_turma',
            field=models.ForeignKey(db_column='id_turma', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Resposta.id_turma+', to='lms.Questao'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='numero_questao',
            field=models.ForeignKey(db_column='numero_questao', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Resposta.numero_questao+', to='lms.Questao'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='ra_aluno',
            field=models.ForeignKey(db_column='ra_aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='lms.Aluno'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='semestre_ofertado',
            field=models.ForeignKey(db_column='semestre_ofertado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Resposta.semestre_ofertado+', to='lms.Questao'),
        ),
        migrations.AlterUniqueTogether(
            name='questao',
            unique_together=set([('nome_disciplina', 'ano_ofertado', 'semestre_ofertado', 'id_turma', 'numero')]),
        ),
        migrations.AlterUniqueTogether(
            name='periododisciplina',
            unique_together=set([('sigla_curso', 'ano_grade', 'semestre_grade', 'numero_periodo', 'nome_disciplina')]),
        ),
        migrations.AddField(
            model_name='arquivoresposta',
            name='ano_ofertado',
            field=models.ForeignKey(db_column='ano_ofertado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Arquivoresposta.ano_ofertado+', to='lms.Questao'),
        ),
        migrations.AddField(
            model_name='arquivoresposta',
            name='id_turma',
            field=models.ForeignKey(db_column='id_turma', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Arquivoresposta.id_turma+', to='lms.Questao'),
        ),
        migrations.AddField(
            model_name='arquivoresposta',
            name='numero_questao',
            field=models.ForeignKey(db_column='numero_questao', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Arquivoresposta.numero_questao+', to='lms.Questao'),
        ),
        migrations.AddField(
            model_name='arquivoresposta',
            name='ra_aluno',
            field=models.ForeignKey(db_column='ra_aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='lms.Aluno'),
        ),
        migrations.AddField(
            model_name='arquivoresposta',
            name='semestre_ofertado',
            field=models.ForeignKey(db_column='semestre_ofertado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Arquivoresposta.semestre_ofertado+', to='lms.Questao'),
        ),
        migrations.AddField(
            model_name='arquivoquestao',
            name='ano_ofertado',
            field=models.ForeignKey(db_column='ano_ofertado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Arquivoquestao.ano_ofertado+', to='lms.Questao'),
        ),
        migrations.AddField(
            model_name='arquivoquestao',
            name='id_turma',
            field=models.ForeignKey(db_column='id_turma', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Arquivoquestao.id_turma+', to='lms.Questao'),
        ),
        migrations.AddField(
            model_name='arquivoquestao',
            name='numero_questao',
            field=models.ForeignKey(db_column='numero_questao', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Arquivoquestao.numero_questao+', to='lms.Questao'),
        ),
        migrations.AddField(
            model_name='arquivoquestao',
            name='semestre_ofertado',
            field=models.ForeignKey(db_column='semestre_ofertado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Arquivoquestao.semestre_ofertado+', to='lms.Questao'),
        ),
        migrations.AlterUniqueTogether(
            name='resposta',
            unique_together=set([('nome_disciplina', 'ano_ofertado', 'semestre_ofertado', 'id_turma', 'numero_questao', 'ra_aluno')]),
        ),
        migrations.AlterUniqueTogether(
            name='arquivoresposta',
            unique_together=set([('nome_disciplina', 'ano_ofertado', 'semestre_ofertado', 'id_turma', 'numero_questao', 'ra_aluno', 'arquivo')]),
        ),
        migrations.AlterUniqueTogether(
            name='arquivoquestao',
            unique_together=set([('nome_disciplina', 'ano_ofertado', 'semestre_ofertado', 'id_turma', 'numero_questao', 'arquivo')]),
        ),
    ]
