# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import testando.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=50)),
                ('ra', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=150)),
                ('perfil', models.CharField(default='C', max_length=1)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', testando.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False, verbose_name='id_curso')),
                ('ativo', models.BooleanField(default=True)),
                ('sigla', models.CharField(max_length=5, unique=True, verbose_name='sigla')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='nome')),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240, unique=True, verbose_name='nome')),
                ('carga_horaria', models.IntegerField(verbose_name='carga_horaria')),
                ('teoria', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='teoria')),
                ('pratica', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='pratica')),
                ('ementa', models.CharField(max_length=500, verbose_name='ementa')),
                ('competencias', models.CharField(max_length=500, verbose_name='competencias')),
                ('habilidades', models.CharField(max_length=500, verbose_name='habilidades')),
                ('conteudo', models.CharField(max_length=500, verbose_name='conteudo')),
                ('bibliografia_basica', models.CharField(max_length=500, verbose_name='bibliografia basica')),
                ('bibliografia_complementar', models.CharField(max_length=500, verbose_name='bibliografia complementar')),
            ],
            options={
                'db_table': 'disciplina',
            },
        ),
        migrations.CreateModel(
            name='Gradecurricular',
            fields=[
                ('id_gradecurricular', models.AutoField(primary_key=True, serialize=False, verbose_name='id_gradecurricular')),
                ('ano', models.SmallIntegerField()),
                ('semestre', models.CharField(max_length=1)),
                ('sigla_curso', models.ForeignKey(db_column='sigla_curso', on_delete=django.db.models.deletion.CASCADE, related_name='sigla_curso', to='testando.Curso')),
            ],
            options={
                'db_table': 'gradecurricular',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False, verbose_name='id_periodo')),
                ('numero', models.IntegerField(verbose_name='numero')),
                ('ano_grade', models.ForeignKey(db_column='ano_grade', on_delete=django.db.models.deletion.CASCADE, related_name='ano_grade', to='testando.Gradecurricular')),
                ('semestre_grade', models.ForeignKey(db_column='semestre_grade', on_delete=django.db.models.deletion.CASCADE, related_name='semestre_grade', to='testando.Gradecurricular')),
                ('sigla_curso', models.ForeignKey(db_column='sigla_curso', on_delete=django.db.models.deletion.CASCADE, related_name='psigla_curso', to='testando.Curso')),
            ],
            options={
                'db_table': 'periodo',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.CharField(max_length=80, verbose_name='email')),
                ('celular', models.CharField(max_length=11, verbose_name='celular')),
                ('sigla_curso', models.ForeignKey(db_column='sigla_curso', on_delete=django.db.models.deletion.CASCADE, related_name='asigla_curso', to='testando.Curso')),
            ],
            options={
                'db_table': 'Aluno',
            },
            bases=('testando.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('apelido', models.CharField(max_length=30, unique=True, verbose_name='apelido')),
                ('email', models.CharField(max_length=80, verbose_name='email')),
                ('celular', models.CharField(max_length=11, verbose_name='celular')),
            ],
            options={
                'db_table': 'professor',
            },
            bases=('testando.usuario',),
        ),
    ]
