# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 01:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import testando.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=50)),
                ('ra', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=150)),
                ('perfil', models.CharField(default='C', max_length=1)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', testando.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False, verbose_name='id_curso')),
                ('ativo', models.BooleanField(default=True)),
                ('sigla', models.CharField(max_length=5, unique=True, verbose_name='sigla')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='nome')),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='Cursoturma',
            fields=[
                ('id_cursoturma', models.AutoField(primary_key=True, serialize=False, verbose_name='id_cursoturma')),
            ],
            options={
                'db_table': 'cursoturma',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240, unique=True, verbose_name='nome')),
                ('carga_horaria', models.IntegerField(verbose_name='carga_horaria')),
                ('teoria', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='teoria')),
                ('pratica', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='pratica')),
                ('ementa', models.CharField(max_length=500, verbose_name='ementa')),
                ('competencias', models.CharField(max_length=500, verbose_name='competencias')),
                ('habilidades', models.CharField(max_length=500, verbose_name='habilidades')),
                ('conteudo', models.CharField(max_length=500, verbose_name='conteudo')),
                ('bibliografia_basica', models.CharField(max_length=500, verbose_name='bibliografia basica')),
                ('bibliografia_complementar', models.CharField(max_length=500, verbose_name='bibliografia complementar')),
            ],
            options={
                'db_table': 'disciplina',
            },
        ),
        migrations.CreateModel(
            name='Disciplinaofertada',
            fields=[
                ('id_disciplinaofertada', models.AutoField(primary_key=True, serialize=False, verbose_name='id_disciplinaofertada')),
                ('ano', models.SmallIntegerField(verbose_name='ano')),
                ('semestre', models.CharField(max_length=1, verbose_name='semestre')),
                ('nome_disciplina', models.ForeignKey(db_column='nome_disciplina', on_delete=django.db.models.deletion.CASCADE, related_name='nome_disciplina', to='testando.Disciplina', unique=True)),
            ],
            options={
                'db_table': 'disciplinaofertada',
            },
        ),
        migrations.CreateModel(
            name='Gradecurricular',
            fields=[
                ('id_gradecurricular', models.AutoField(primary_key=True, serialize=False, verbose_name='id_gradecurricular')),
                ('ano', models.SmallIntegerField()),
                ('semestre', models.CharField(max_length=1)),
                ('sigla_curso', models.ForeignKey(db_column='sigla_curso', on_delete=django.db.models.deletion.CASCADE, related_name='sigla_curso', to='testando.Curso')),
            ],
            options={
                'db_table': 'gradecurricular',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False, verbose_name='id_matricula')),
                ('ano_ofertado', models.ForeignKey(db_column='ano_ofertado', on_delete=django.db.models.deletion.CASCADE, related_name='mano_ofertado', to='testando.Disciplinaofertada')),
            ],
            options={
                'db_table': 'matricula',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False, verbose_name='id_periodo')),
                ('numero', models.IntegerField(verbose_name='numero')),
                ('ano_grade', models.ForeignKey(db_column='ano_grade', on_delete=django.db.models.deletion.CASCADE, related_name='ano_grade', to='testando.Gradecurricular')),
                ('semestre_grade', models.ForeignKey(db_column='semestre_grade', on_delete=django.db.models.deletion.CASCADE, related_name='semestre_grade', to='testando.Gradecurricular')),
                ('sigla_curso', models.ForeignKey(db_column='sigla_curso', on_delete=django.db.models.deletion.CASCADE, related_name='psigla_curso', to='testando.Curso')),
            ],
            options={
                'db_table': 'periodo',
            },
        ),
        migrations.CreateModel(
            name='Periododisciplina',
            fields=[
                ('id_periododisciplina', models.AutoField(primary_key=True, serialize=False, verbose_name='id_periododisciplina')),
                ('ano_grade', models.ForeignKey(db_column='ano_grade', on_delete=django.db.models.deletion.CASCADE, related_name='pdano_grade', to='testando.Gradecurricular')),
                ('nome_disciplina', models.ForeignKey(db_column='nome_disciplina', on_delete=django.db.models.deletion.CASCADE, related_name='pdnome_disciplina', to='testando.Disciplina')),
                ('numero_periodo', models.ForeignKey(db_column='numero_periodo', on_delete=django.db.models.deletion.CASCADE, related_name='pdnumero_periodo', to='testando.Periodo')),
                ('semestre_grade', models.ForeignKey(db_column='semestre_grade', on_delete=django.db.models.deletion.CASCADE, related_name='pdsemestre_grade', to='testando.Gradecurricular')),
                ('sigla_curso', models.ForeignKey(db_column='sigla_curso', on_delete=django.db.models.deletion.CASCADE, related_name='pdsigla_curso', to='testando.Curso')),
            ],
            options={
                'db_table': 'periododisciplina',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('entrega', models.DateField(verbose_name='Entrega')),
                ('arquivo', models.FileField(upload_to='arquivos/')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False, verbose_name='id_turma')),
                ('turma_sigla', models.CharField(max_length=1, unique=True)),
                ('turno', models.CharField(max_length=15, verbose_name='turno')),
                ('ano_ofertado', models.ForeignKey(db_column='ano_ofertado', on_delete=django.db.models.deletion.CASCADE, related_name='tano_ofertado', to='testando.Disciplinaofertada')),
                ('nome_disciplina', models.ForeignKey(db_column='nome_disciplina', on_delete=django.db.models.deletion.CASCADE, related_name='tnome_disciplina', to='testando.Disciplina')),
                ('semestre_ofertado', models.ForeignKey(db_column='semestre_ofertado', on_delete=django.db.models.deletion.CASCADE, related_name='tsemestre_ofertado', to='testando.Disciplinaofertada')),
            ],
            options={
                'db_table': 'turma',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.CharField(max_length=80, verbose_name='email')),
                ('celular', models.CharField(max_length=11, verbose_name='celular')),
                ('sigla_curso', models.ForeignKey(db_column='sigla_curso', on_delete=django.db.models.deletion.CASCADE, related_name='asigla_curso', to='testando.Curso')),
            ],
            options={
                'db_table': 'Aluno',
            },
            bases=('testando.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('apelido', models.CharField(max_length=30, unique=True, verbose_name='apelido')),
                ('email', models.CharField(max_length=80, verbose_name='email')),
                ('celular', models.CharField(max_length=11, verbose_name='celular')),
            ],
            options={
                'db_table': 'professor',
            },
            bases=('testando.usuario',),
        ),
        migrations.AddField(
            model_name='questao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testando.Turma'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='cod_turma',
            field=models.ForeignKey(db_column='cod_turma', on_delete=django.db.models.deletion.CASCADE, related_name='mcod_turma', to='testando.Turma'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='nome_disciplina',
            field=models.ForeignKey(db_column='nome_disciplina', on_delete=django.db.models.deletion.CASCADE, related_name='mnome_disciplina', to='testando.Disciplina'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='semestre_ofertado',
            field=models.ForeignKey(db_column='semestre_ofertado', on_delete=django.db.models.deletion.CASCADE, related_name='msemestre_ofertado', to='testando.Disciplinaofertada'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='ano_ofertado',
            field=models.ForeignKey(db_column='ano_ofertado', on_delete=django.db.models.deletion.CASCADE, related_name='ctano_ofertado', to='testando.Disciplinaofertada'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='cod_turma',
            field=models.ForeignKey(db_column='cod_turma', on_delete=django.db.models.deletion.CASCADE, related_name='ctcod_turma', to='testando.Turma'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='nome_disciplina',
            field=models.ForeignKey(db_column='nome_disciplina', on_delete=django.db.models.deletion.CASCADE, related_name='ctnome_disciplina', to='testando.Disciplina'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='semestre_ofertado',
            field=models.ForeignKey(db_column='semestre_ofertado', on_delete=django.db.models.deletion.CASCADE, related_name='ctsemestre_ofertado', to='testando.Disciplinaofertada'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='sigla_curso',
            field=models.ForeignKey(db_column='sigla_curso', on_delete=django.db.models.deletion.CASCADE, to='testando.Curso'),
        ),
        migrations.AddField(
            model_name='turma',
            name='ra_professor',
            field=models.ForeignKey(db_column='ra_professor', on_delete=django.db.models.deletion.CASCADE, related_name='tra_professor', to='testando.Professor'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ra_aluno',
            field=models.ForeignKey(db_column='ra_aluno', on_delete=django.db.models.deletion.CASCADE, to='testando.Aluno'),
        ),
    ]
