# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import testando.models


class Migration(migrations.Migration):

    dependencies = [
        ('testando', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='arquivo',
            field=models.FileField(upload_to=testando.models.monta_arquivo),
        ),
    ]
