# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testando', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinaofertada',
            fields=[
                ('id_disciplinaofertada', models.AutoField(primary_key=True, serialize=False, verbose_name='id_disciplinaofertada')),
                ('ano', models.SmallIntegerField(verbose_name='ano')),
                ('semestre', models.CharField(max_length=1, verbose_name='semestre')),
                ('nome_disciplina', models.ForeignKey(db_column='nome_disciplina', on_delete=django.db.models.deletion.CASCADE, related_name='nome_disciplina', to='testando.Disciplina', unique=True)),
            ],
            options={
                'db_table': 'disciplinaofertada',
            },
        ),
    ]
