# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testando', '0002_disciplinaofertada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periododisciplina',
            fields=[
                ('id_periododisciplina', models.AutoField(primary_key=True, serialize=False, verbose_name='id_periododisciplina')),
                ('ano_grade', models.ForeignKey(db_column='ano_grade', on_delete=django.db.models.deletion.CASCADE, related_name='pdano_grade', to='testando.Gradecurricular')),
                ('nome_disciplina', models.ForeignKey(db_column='nome_disciplina', on_delete=django.db.models.deletion.CASCADE, related_name='pdnome_disciplina', to='testando.Disciplina')),
                ('numero_periodo', models.ForeignKey(db_column='numero_periodo', on_delete=django.db.models.deletion.CASCADE, related_name='pdnumero_periodo', to='testando.Periodo')),
                ('semestre_grade', models.ForeignKey(db_column='semestre_grade', on_delete=django.db.models.deletion.CASCADE, related_name='pdsemestre_grade', to='testando.Gradecurricular')),
                ('sigla_curso', models.ForeignKey(db_column='sigla_curso', on_delete=django.db.models.deletion.CASCADE, related_name='pdsigla_curso', to='testando.Curso')),
            ],
            options={
                'db_table': 'periododisciplina',
            },
        ),
    ]
