# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import testando.models


class Migration(migrations.Migration):

    dependencies = [
        ('testando', '0002_auto_20171128_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrega', models.DateField(verbose_name='Entrega')),
                ('arquivo', models.FileField(upload_to=testando.models.monta_arquivo)),
                ('data_de_envio', models.DateField(verbose_name='data_de_envio')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testando.Aluno')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testando.Questao')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testando.Turma')),
            ],
        ),
    ]
