# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testando', '0003_periododisciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False, verbose_name='id_turma')),
                ('turma', models.CharField(max_length=1, verbose_name='turma')),
                ('turno', models.CharField(max_length=15, verbose_name='turno')),
                ('ano_ofertado', models.ForeignKey(db_column='ano_ofertado', on_delete=django.db.models.deletion.CASCADE, related_name='tano_ofertado', to='testando.Disciplinaofertada')),
                ('nome_disciplina', models.ForeignKey(db_column='nome_disciplina', on_delete=django.db.models.deletion.CASCADE, related_name='tnome_disciplina', to='testando.Disciplina')),
                ('ra_professor', models.ForeignKey(db_column='ra_professor', on_delete=django.db.models.deletion.CASCADE, related_name='tra_professor', to='testando.Professor')),
                ('semestre_ofertado', models.ForeignKey(db_column='semestre_ofertado', on_delete=django.db.models.deletion.CASCADE, related_name='tsemestre_ofertado', to='testando.Disciplinaofertada')),
            ],
            options={
                'db_table': 'turma',
            },
        ),
    ]
