# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testando', '0005_cursoturma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False, verbose_name='id_matricula')),
                ('ano_ofertado', models.ForeignKey(db_column='ano_ofertado', on_delete=django.db.models.deletion.CASCADE, related_name='mano_ofertado', to='testando.Disciplinaofertada')),
                ('cod_turma', models.ForeignKey(db_column='cod_turma', on_delete=django.db.models.deletion.CASCADE, related_name='mcod_turma', to='testando.Turma')),
                ('nome_disciplina', models.ForeignKey(db_column='nome_disciplina', on_delete=django.db.models.deletion.CASCADE, related_name='mnome_disciplina', to='testando.Disciplina')),
                ('ra_aluno', models.ForeignKey(db_column='ra_aluno', on_delete=django.db.models.deletion.CASCADE, to='testando.Aluno')),
                ('semestre_ofertado', models.ForeignKey(db_column='semestre_ofertado', on_delete=django.db.models.deletion.CASCADE, related_name='msemestre_ofertado', to='testando.Disciplinaofertada')),
            ],
            options={
                'db_table': 'matricula',
            },
        ),
    ]
