# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testando', '0006_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id_questao', models.AutoField(primary_key=True, serialize=False, verbose_name='id_questao')),
                ('numero', models.IntegerField(verbose_name='numero')),
                ('descricao', models.CharField(max_length=750, verbose_name='descricao')),
                ('data_limite_entrega', models.DateField(verbose_name='data_limite_entrega')),
                ('arquivo', models.FileField(upload_to='')),
                ('ano_ofertado', models.ForeignKey(db_column='ano_ofertado', on_delete=django.db.models.deletion.CASCADE, related_name='qano_ofertado', to='testando.Disciplinaofertada')),
                ('cod_turma', models.ForeignKey(db_column='id_turma', on_delete=django.db.models.deletion.CASCADE, related_name='qid_turma', to='testando.Turma')),
                ('nome_disciplina', models.ForeignKey(db_column='nome_disciplina', on_delete=django.db.models.deletion.CASCADE, related_name='qnome_disciplina', to='testando.Disciplina')),
                ('semestre_ofertado', models.ForeignKey(db_column='semestre_ofertado', on_delete=django.db.models.deletion.CASCADE, related_name='qsemestre_ofertado', to='testando.Disciplinaofertada')),
            ],
            options={
                'db_table': 'questao',
            },
        ),
    ]
